### ISSUE TITLE
Where is my index.js?

### ISSUE THREAD

**Issue by bhoov** [philter87/publish-svelte#4]
Seems like a really great package, just started trying it out.

I have an existing project with a component i want to publish at `/src/components/MyComponent.svelte`. Following the instructions, I `cd /src/components` and run `pelte ./MyComponent.svelte --skip-publish --keep-bundle`. This creates a directory `/src/components/MyComponent` which contains a `README.md` and a `package.json`, in addition to a `/src/components/MyComponent.json` file. There is no `index.js` file anywhere. What is the issue?

If it helps with debugging, `MyComponent.svelte` uses Typescript `<script lang='ts'>` tag.

**Comment by philter87** [comment]
Thanks for opening an issue. The note about typescript is spot on, because pelte is missing typescript support. Hopefully, I will be able to add this in a couple of days.

**Comment by philter87** [comment]
Hi bhoov.
That was a tricky one, but I hope I have fixed the bug now. Use the latest version of publish-svelte 0.6.0.

**Comment by bhoov** [comment]
Great thanks for getting on that so quickly! I now see there is a `tsconfig.json` in the `MyComponent` directory, and this is the only difference as far as I can see.

This is also my first time publishing anything to npm so I might need a little more handholding in the instructions. Do I need to manually create an `index.js`? What are my next steps after generating?

**Comment by philter87** [comment]
I think you have done eveything correct. Maybe there is another bug, I only tested the change on a very simpel svelte component. Can you provide a codesnippet for the component?

**Comment by philter87** [comment]
Maybe you can try pelte on a very simple svelte component. If you run with the --keep-bundle flag, it is suppose to create the index.js file automatically. Furthermore, it will create a html file, that shows how to use the svelte component.

**Comment by bhoov** [comment]
Hmm interesting. `pelte` definitely works on simple typescript components, kudos! I think I can better describe my problem then:

The following error happens when I try to import an external `utils.ts` file from outside the component:

```
node:35949) UnhandledPromiseRejectionWarning: Error: Could not resolve './utils' from App.svelte
    at error (/usr/local/lib/node_modules/publish-svelte/node_modules/rollup/dist/shared/rollup.js:5211:30)
    at ModuleLoader.handleResolveId (/usr/local/lib/node_modules/publish-svelte/node_modules/rollup/dist/shared/rollup.js:18246:24)
    at /usr/local/lib/node_modules/publish-svelte/node_modules/rollup/dist/shared/rollup.js:18238:22
    at async Promise.all (index 1)
    at async ModuleLoader.fetchStaticDependencies (/usr/local/lib/node_modules/publish-svelte/node_modules/rollup/dist/shared/rollup.js:18236:34)
    at async Promise.all (index 0)
    at async ModuleLoader.fetchModule (/usr/local/lib/node_modules/publish-svelte/node_modules/rollup/dist/shared/rollup.js:18213:9)
    at async Promise.all (index 0)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:35949) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:35949) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

And, of course, no index.js is generated even when the `--keep-bundle` flag is given. Thoughts?

**Comment by philter87** [comment]
Yeah, I might know what the problem and you have seem to have figured it out aswell. My tool is only able to compile typescript inside the svelte components. I will need to add another roll-up plugin to handle typescript files. I tried to add this plugin, but I got an error which was caused by a bug in the plugin: https://github.com/rollup/plugins/issues/243 
I will try to take another look, but unfortunately it will likely take a couple of days. I am sorry for the inconvience but thanks for reporting this stuff - it is a greet help.

**Comment by bhoov** [comment]
I'm glad I can help! Thank you very much for your responsiveness. If you need me to test anything out for you I will gladly do so. Best of luck!

**Comment by philter87** [comment]
If it is possible, then maybe you can try and move the typescript logic inside your svelte component.

**Comment by bhoov** [comment]
Yep I did and worked great! For this first component I did not have much typescript logic, but I was hoping to port a slightly more complicated component soon. TBH this tool is incredibly helpful, especially for first time component makers like myself. Thank you for your work!

**Comment by philter87** [comment]
Thanks - that means a lot to me. I will try to fix the bug as soon as possible.

**Comment by bhoov** [comment]
Any updates? Would love to include this in a presentation to my team at the end of next week if we can easily publish complex components. If not, I think I can still sell them on Svelte but this would be some serious icing on that cake :)

**Comment by philter87** [comment]
Hi bhoov
I am sorry, I have no updates. I tried two different things but it didnt work. I think I will need to wait until the bug in the dependeny is fixed.
It is a bummer, because I love the idea of my tool being part of a demo.

**Comment by bhoov** [comment]
No worries! Might not be on our timeline but I'd still like to show this to them when things are fixed upstream. Thanks again!
